Combine files into single object

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import glob

citibike_files = glob.glob('data/JC*.csv')

df_list = []

# create unified dataframe from all the citibike files
for filename in citibike_files:
    raw_data = pd.read_csv(filename)
    df_list.append(raw_data)

citibike_df = pd.concat(df_list, axis=0)

# reset the index after concatenation
citibike_df.reset_index(drop=True, inplace=True)

# create ID column
citibike_df['id'] = citibike_df.index +1

inspect the beginning and end of the dataset

In [2]:
citibike_df.head(3)

,Trip Duration,Start Time,Stop Time,Start Station ID,Start Station Name,Start Station Latitude,Start Station Longitude,End Station ID,End Station Name,End Station Latitude,End Station Longitude,Bike ID,User Type,Birth Year,Gender,id
0,361,2016-02-01 00:31:18,2016-02-01 00:37:19,3202,Newport PATH,40.727224,-74.033759,3203,Hamilton Park,40.727596,-74.044247,24393,Subscriber,1975.0,1,1
1,297,2016-02-01 01:55:05,2016-02-01 02:00:02,3195,Sip Ave,40.730743,-74.063784,3194,McGinley Square,40.725340,-74.067622,24394,Subscriber,1985.0,2,2
2,1155,2016-02-01 02:40:05,2016-02-01 02:59:20,3183,Exchange Place,40.716247,-74.033459,3210,Pershing Field,40.742677,-74.051789,24676,Subscriber,1976.0,1,3

In [3]:
citibike_df.tail(3)

,Trip Duration,Start Time,Stop Time,Start Station ID,Start Station Name,Start Station Latitude,Start Station Longitude,End Station ID,End Station Name,End Station Latitude,End Station Longitude,Bike ID,User Type,Birth Year,Gender,id
247581,2048,2016-05-31 23:25:28,2016-05-31 23:59:36,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,24573,Subscriber,1975.0,1,247582
247582,455,2016-05-31 23:31:57,2016-05-31 23:39:32,3220,5 Corners Library,40.734961,-74.059503,3215,Central Ave,40.746730,-74.049251,24561,Subscriber,1964.0,1,247583
247583,239,2016-05-31 23:47:38,2016-05-31 23:51:37,3185,City Hall,40.717732,-74.043845,3211,Newark Ave,40.721525,-74.046305,24685,Subscriber,1993.0,1,247584

Convert Gender to human readable format

In [9]:
citibike_df.describe()
citibike_df.info()
citibike_df.isna().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 247584 entries, 0 to 247583
Data columns (total 16 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Trip Duration            247584 non-null  int64
 1   Start Time               247584 non-null  datetime64[ns]
 2   Stop Time                247584 non-null  datetime64[ns]
 3   Start Station ID         247584 non-null  int64
 4   Start Station Name       247584 non-null  object
 5   Start Station Latitude   247584 non-null  float64
 6   Start Station Longitude  247584 non-null  float64
 7   End Station ID           247584 non-null  int64
 8   End Station Name         247584 non-null  object
 9   End Station Latitude     247584 non-null  float64
 10  End Station Longitude    247584 non-null  float64
 11  Bike ID                  247584 non-null  int64
 12  User Type                247204 non-null  object
 13  Birth Year               228585 non-null  float64
 14  Gender                   247584 non-null  object
 15  id                       247584 non-null  int64
dtypes: datetime64[ns](2), float64(5), int64(5), object(4)
memory usage: 30.2+ MB

Trip Duration                  0
Start Time                     0
Stop Time                      0
Start Station ID               0
Start Station Name             0
Start Station Latitude         0
Start Station Longitude        0
End Station ID                 0
End Station Name               0
End Station Latitude           0
End Station Longitude          0
Bike ID                        0
User Type                    380
Birth Year                 18999
Gender                         0
id                             0
dtype: int64

In [11]:
citibike_df["Gender"] = citibike_df["Gender"].astype(str).str.replace('1','Male').str.replace('2','Female')
citibike_df["Start Time"] = pd.to_datetime(citibike_df["Start Time"])
citibike_df["Stop Time"] = pd.to_datetime(citibike_df["Stop Time"])

# citibike_df.dtypes()
citibike_df.head()

,Trip Duration,Start Time,Stop Time,Start Station ID,Start Station Name,Start Station Latitude,Start Station Longitude,End Station ID,End Station Name,End Station Latitude,End Station Longitude,Bike ID,User Type,Birth Year,Gender,id
0,361,2016-02-01 00:31:18,2016-02-01 00:37:19,3202,Newport PATH,40.727224,-74.033759,3203,Hamilton Park,40.727596,-74.044247,24393,Subscriber,1975.0,Male,1
1,297,2016-02-01 01:55:05,2016-02-01 02:00:02,3195,Sip Ave,40.730743,-74.063784,3194,McGinley Square,40.725340,-74.067622,24394,Subscriber,1985.0,Female,2
2,1155,2016-02-01 02:40:05,2016-02-01 02:59:20,3183,Exchange Place,40.716247,-74.033459,3210,Pershing Field,40.742677,-74.051789,24676,Subscriber,1976.0,Male,3
3,1769,2016-02-01 05:11:28,2016-02-01 05:40:58,3214,Essex Light Rail,40.712774,-74.036486,3203,Hamilton Park,40.727596,-74.044247,24700,Subscriber,1974.0,Female,4
4,935,2016-02-01 05:48:24,2016-02-01 06:03:59,3203,Hamilton Park,40.727596,-74.044247,3214,Essex Light Rail,40.712774,-74.036486,24639,Subscriber,1974.0,Female,5

In [6]:
citibike_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 247584 entries, 0 to 247583
Data columns (total 16 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Trip Duration            247584 non-null  int64
 1   Start Time               247584 non-null  datetime64[ns]
 2   Stop Time                247584 non-null  datetime64[ns]
 3   Start Station ID         247584 non-null  int64
 4   Start Station Name       247584 non-null  object
 5   Start Station Latitude   247584 non-null  float64
 6   Start Station Longitude  247584 non-null  float64
 7   End Station ID           247584 non-null  int64
 8   End Station Name         247584 non-null  object
 9   End Station Latitude     247584 non-null  float64
 10  End Station Longitude    247584 non-null  float64
 11  Bike ID                  247584 non-null  int64
 12  User Type                247204 non-null  object
 13  Birth Year               228585 non-null  float64
 14  Gender                   247584 non-null  object
 15  id                       247584 non-null  int64
dtypes: datetime64[ns](2), float64(5), int64(5), object(4)
memory usage: 30.2+ MB

Remove null values